language: python

# Use container-based infrastructure
sudo: false

matrix:
  fast_finish: true
  include:
    - python: pypy
    - python: pypy3
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.6
    - python: 3.5
    - python: 3.4
    - python: 2.7

install:
 - pip install -r requirements.txt
 - pip install coverage

script:
 - coverage run --source=tracery -m nose tests/test_*.py

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
 - pip install pycodestyle pyflakes
 - pyflakes . | tee >(wc -l)
 - pycodestyle --statistics --count .
